[project]
name = "luxdb"
version = "1.0.Ω"
description = "LuxDB - Modular database system from the Astral lineage"
authors = [{ name = "Oriom (ΩO)", email = "luxoriom@proton.me" }]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.1",
    "sqlalchemy>=2.0.41",
]