[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.1",
    "sqlalchemy>=2.0.41",
]
